spring:
  profiles:
    active: dev
  application:
    name: teamplatform-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/team_platform?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    port: 6379
    host: localhost
    database: 1
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
knife4j:
  enable: true
  openapi:
    title: 小白交友组队平台
    description: 小白交友组队平台后端接口
    email: youcode@foxmail.com
    concat: baichenbo
    url:
    version: v1.0
    license: Apache 2.0
    terms-of-service-url: https://github.com/baichenbo
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.example.teamplatform.controller
